apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: cicd-test
build:
  artifacts:
  - image: cicd-test
    docker:
      dockerfile: Dockerfile
  local:
    useBuildkit: true
deploy:
  kubectl:
    manifests:
    - k8s/*.yaml
