apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "cicd-test.name" . }}
  labels:
    {{- include "cicd-test.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: PathPrefix(`/cicd-test`)
      middlewares:
        - name: {{ include "cicd-test.name" . }}
      services:
        - kind: Service
          name: {{ include "cicd-test.name" . }}
          port: 80