apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ include "cicd-test.name" . }}
  labels:
    {{- include "cicd-test.labels" . | nindent 4 }}
spec:
  stripPrefix:
    prefixes:
      - /cicd-test