apiVersion: v1
kind: Service
metadata:
  name: {{ include "cicd-test.name" . }}
  labels:
    {{- include "cicd-test.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    {{- include "cicd-test.selectorLabels" . | nindent 4 }}